# Generated by Django 4.1.7 on 2023-02-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_rename_question_posted_by_question_posted_by_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Question",
            new_name="Questions",
        ),
    ]
